Project/Project/admins/routes.py
from flask import Blueprint, redirect, render_template, url_for, flash, current_app
from flask_login import current_user, login_required
from Project import db, bcrypt
from Project.models import Admin, Student
from Project.admins.forms import updateAdminForm, addStudentForm
from Project.admins.utils import save_picture, get_dataset, prepare_training_data
import os
import json
import cv2
import numpy as np

admins = Blueprint('admins', __name__)

@admins.route('/admin_update', methods = ['GET', 'POST'])
@login_required
def admin_update():
    if current_user.is_authenticated:
        if current_user.is_allowed(2)==0:
            return redirect(url_for('home'))
    form = updateAdminForm()
    if form.validate_on_submit():
        admin = Admin.query.filter_by(admin_id=form.admin_id.data).first()
        if admin:
            picture_file = save_picture(form.image.data,2)
            admin.image_file=picture_file
            print(admin.image_file)
            db.session.commit()
            return redirect(url_for('main.logout'))
    else:
        flash('Please enter correct details', 'danger')
    return render_template('admin_update.html', title = 'Update Admin', form=form)

@admins.route('/admin_entry', methods = ['GET', 'POST'])
@login_required
def admin_entry():
    if not current_user.is_allowed(2):
        return redirect(url_for('students.outpass_form'))
    form = addStudentForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        picture_file = save_picture(form.image.data,1)
        student = Student(student_id=form.enrol_no.data, name = form.name.data, password=hashed_password, hostel=form.hostel_no.data,\
                        guardian_name=form.guardian_name.data, guardian_contact=form.guardian_contact.data,\
                            image_file = picture_file)
        
        path = os.path.join(current_app.root_path,'static/recognition',form.enrol_no.data)
        os.makedirs(path)

        get_dataset(path)
        prepare_training_data(path,form.enrol_no.data)

        file_path = os.path.join(current_app.root_path, 'ML_model.json')
        test_file = open(file_path,'r')
        data = json.load(test_file)
        list_arrays = data["faces"]
        list1=[]
        for array in list_arrays:
            array = np.array(array, dtype=np.uint8)
            list1.append(array)

        test_file.close()
        recognition = cv2.face.LBPHFaceRecognizer_create()
        recognition.train(list1, np.array(data["labels"]))

        db.session.add(student)
        db.session.commit()
        flash('The student has been added to the database', 'success')
        return redirect(url_for('admins.admin_entry'))
    else:
        flash('Please enter correct details', 'danger')
    return render_template('admin_entry.html', title = 'Student Entry', form=form)

Project/Project/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_user, logout_user
from Project import bcrypt, session, db
from Project.main.forms import LoginForm, PermissionForm
from Project.models import Student, Admin
from Project.main.utils import predict_final
import datetime

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home', methods = ['GET', 'POST'])
def login_page():
    if current_user.is_authenticated:
        if current_user.is_allowed(1):
            return redirect(url_for('students.outpass_form'))
        return redirect(url_for('admins.admin_entry'))
    form = LoginForm()
    if form.validate_on_submit():
        student = Student.query.filter_by(student_id=form.id.data).first()
        if student and bcrypt.check_password_hash(student.password, form.password.data):
            session['account_type'] = 'Student'
            login_user(student, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('students.outpass_form'))
    else:
        flash('Please enter correct details', 'danger')
    return render_template('login.html', title = 'Outpass Login', form=form)

@main.route('/face_login', methods = ['GET', 'POST'])
def face_login():
    if current_user.is_authenticated:
        if current_user.is_allowed(1):
            return redirect(url_for('students.outpass_form'))
        return redirect(url_for('admins.admin_entry'))
    enrolment = predict_final()
    if enrolment is not None:
        student = Student.query.filter_by(student_id=enrolment).first()
        if student :
            session['account_type'] = 'Student'
            login_user(student)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('students.outpass_form'))
    else:
        flash('Please enter correct details', 'danger')
    return render_template('face_login.html', title = 'Outpass Login')

@main.route('/admin_login', methods = ['GET', 'POST'])
def admin_login():
    if current_user.is_authenticated:
        if current_user.is_allowed(2):
            return redirect(url_for('admins.admin_entry'))
        return redirect(url_for('students.outpass_form'))
    form = LoginForm()
    if form.validate_on_submit():
        admin = Admin.query.filter_by(admin_id=form.id.data).first()
        if admin and bcrypt.check_password_hash(admin.password, form.password.data):
            session['account_type'] = 'Admin'
            login_user(admin, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('admins.admin_entry'))
    else:
        flash('Please enter correct details', 'danger')
    return render_template('admin_login.html', title = 'Outpass Login', form=form)

@main.route("/permission/<token>", methods=['GET', 'POST'])
def reset_token(token):
    student = Student.verify_reset_token(token)
    if student is None:
        flash('That is an invalid or expired token', 'warning')
        return render_template('errors/404.html')
    form = PermissionForm()
    if request.method == 'POST':
        if request.form['submit1'] == 'Yes':
            student.grant_time = datetime.datetime.utcnow() + datetime.timedelta(hours=5.5)
            print("yes")
        else:
            student.out_time = datetime.datetime.utcnow().strftime('%d-%m-%Y %H:%M:%S')
            print("no")
        db.session.commit()  
        return render_template('permission.html', title='Permission', student=student, form=form)
    return render_template('permission.html', title='Permission', student=student, form=form)

@main.route("/logout")
def logout():
    logout_user()
    if session['account_type']=='Student':
        session['account_type']=None
        return redirect(url_for('main.login_page'))
    session['account_type']=None
    return redirect(url_for('main.admin_login'))

Project/Project/templates/admin_entry.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <a class="topcorner" href="{{url_for('admins.admin_update')}}">Update your creds?</a>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ title }}</legend>
            <div class="grid-container">
                <div>
                    <div class="form-group">
                        {{ form.enrol_no.label(class="form-control-label") }}
                        {% if form.enrol_no.errors %}
                            {{ form.enrol_no(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.enrol_no.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.enrol_no(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.name.label(class="form-control-label") }}
                        {% if form.name.errors %}
                            {{ form.name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.name(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.hostel_no.label(class="form-control-label") }}
                        {% if form.hostel_no.errors %}
                            {{ form.hostel_no(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.hostel_no.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.hostel_no(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.guardian_name.label(class="form-control-label") }}
                        {% if form.guardian_name.errors %}
                            {{ form.guardian_name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.guardian_name.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.guardian_name(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.guardian_contact.label(class="form-control-label") }}
                        {% if form.guardian_contact.errors %}
                            {{ form.guardian_contact(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.guardian_contact.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.guardian_contact(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <div class="form-group">
                            {{ form.image.label() }}
                            {{ form.image(class="form-control-file") }}
                            {% if form.image.errors %}
                                {% for error in form.image.errors %}
                                    <span class="text-danger">{{ error }}</span></br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        
    </form>
</div>

{% endblock %}

Project/Project/templates/admin_login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="{{url_for('main.admin_login')}}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Outpass System</legend>
            <div class="form-group">
                {{ form.id.label(class="form-control-label") }}
                {% if form.id.errors %}
                    {{ form.id(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.id.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.id(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small>
            <a href="{{url_for('main.login_page')}}">Not an Admin?</a>
        </small>
    </form>
</div>

{% endblock %}

Project/Project/templates/admin_update.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <a class="topcorner" href="{{url_for('admins.admin_entry')}}">Add a student?</a>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ title }}</legend>
            <div class="grid-container">
                <div>
                    <div class="form-group">
                        {{ form.admin_id.label(class="form-control-label") }}
                        {% if form.admin_id.errors %}
                            {{ form.admin_id(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.admin_id.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.admin_id(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <div class="form-group">
                            {{ form.image.label() }}
                            {{ form.image(class="form-control-file") }}
                            {% if form.image.errors %}
                                {% for error in form.image.errors %}
                                    <span class="text-danger">{{ error }}</span></br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock %}

Project/Project/templates/allowed.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.student_id }}</h2>
          <p class="text-secondary">{{ current_user.name }}</p>
        </div>
        <img class="rounded-circle account-img" src="{{ image }}">
      </div class=''>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Outpass Form</legend>
                <div class="form-group">
                    {{ form.student_id.label(class="form-control-label") }}

                    {% if form.student_id.errors %}
                        {{ form.student_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.student_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.student_id }}
                        {% else %}
                            {{ form.student_id(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.name }}
                        {% else %}
                            {{ form.name(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.hostel.label(class="form-control-label") }}
                    {% if form.hostel.errors %}
                        {{ form.hostel(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.hostel.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.hostel }}
                        {% else %}
                            {{ form.hostel(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.purpose.label(class="form-control-label") }}
                    {% if form.purpose.errors %}
                        {{ form.purpose(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.purpose.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.purpose }}
                        {% else %}
                            {{ form.purpose(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.out_time.label(class="form-control-label") }}
                    {% if form.out_time.errors %}
                        {{ form.out_time(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.out_time.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.out_time }}
                        {% else %}
                            {{ form.out_time(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="media form-group">
                    {{ form.signature.label(class="form-control-label") }}
                    {% if current_user.sent_form==True %}
                        <img class="sig_size" src="{{ image_file }}">
                    {% endif %}
                    
                </div>
            </fieldset>
            
            <div class="form-group">
                {% if current_user.sent_form==False %}
                    {{ form.submit(class="btn btn-outline-info") }}
                {% endif %}
                
            </div>
        </form>
    </div>
{% endblock content %}

Project/Project/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,  shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style type="text/css">
        .topcorner{
          position:absolute;
          top:8;
          right:7%;
         }
         .sig_size{
            width:200.28346457;
            height:56.692913386;
         }
    </style>
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>IIITA Outpass</title>
    {% endif %}
</head>
<body>
    <div class="container">
        {% if current_user.is_active %}
            <a class="nav-item nav-link" href="{{ url_for('main.logout') }}">Logout</a>
        {% endif %}

        {% block content %}
        {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </div>
</body>
</html>
</body>
</html>

Project/Project/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <a class="topcorner" href="{{url_for('main.face_login')}}" action="#">Forgot password?</a>
    <form method="POST" action="{{url_for('main.login_page')}}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Outpass System</legend>
            <div class="form-group">
                {{ form.id.label(class="form-control-label") }}
                {% if form.id.errors %}
                    {{ form.id(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.id.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.id(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <small>
            <a href="{{url_for('main.admin_login')}}">Not a student?</a>
        </small>
    </form>
</div>

{% endblock %}

Project/Project/templates/outpass_form.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.student_id }}</h2>
          <p class="text-secondary">{{ current_user.name }}</p> 
        </div>
        <img class="rounded-circle account-img" src="{{ image }}">
      </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Outpass Form</legend>
                <div class="form-group">
                    {{ form.student_id.label(class="form-control-label") }}
                    {% if form.student_id.errors %}
                        {{ form.student_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.student_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.student_id }}
                        {% else %}
                            {{ form.student_id(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.name }}
                        {% else %}
                            {{ form.name(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.hostel.label(class="form-control-label") }}
                    {% if form.hostel.errors %}
                        {{ form.hostel(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.hostel.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.hostel }}
                        {% else %}
                            {{ form.hostel(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.purpose.label(class="form-control-label") }}
                    {% if form.purpose.errors %}
                        {{ form.purpose(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.purpose.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.purpose }}
                        {% else %}
                            {{ form.purpose(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.out_time.label(class="form-control-label") }}
                    {% if form.out_time.errors %}
                        {{ form.out_time(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.out_time.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {% if current_user.sent_form==True %}
                            {{ current_user.out_time }}
                        {% else %}
                            {{ form.out_time(class="form-control form-control-lg") }}
                        {% endif %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {% if current_user.sent_form==False %}
                    {{ form.submit(class="btn btn-outline-info") }}
                {% endif %}
                
            </div>
        </form>
    </div>
{% endblock content %}

Project/Project/templates/status.html
{% extends "layout.html" %}
{% block content %}

    <a class="btn btn-warning" href="#" role="button">You have to wait :|</a>

{% endblock %}